-- SPDX-FileCopyrightText: (C) Copyright 2021 CSI Piemonte
--
-- SPDX-License-Identifier: EUPL-1.2

DROP ALL OBJECTS;

CREATE SCHEMA EPOLL;

--sequences
CREATE SEQUENCE EPOLL.EPOLL_T_ELETTORE_ID_SEQ;
CREATE SEQUENCE EPOLL.EPOLL_T_ENTE_ID_SEQ;
CREATE SEQUENCE EPOLL.EPOLL_T_POLL_ID_SEQ;
CREATE SEQUENCE EPOLL.EPOLL_T_PREFERENZA_ID_SEQ;
CREATE SEQUENCE EPOLL.EPOLL_T_PREFERENZA_ESPRESSA_ID_SEQ;
CREATE SEQUENCE EPOLL.EPOLL_T_PRESIDENTE_ID_SEQ;
CREATE SEQUENCE EPOLL.EPOLL_T_PEC_CF_ID_SEQG;
CREATE SEQUENCE EPOLL.EPOLL_T_BODY_PREFERENZA_ID_SEQ;

CREATE TABLE EPOLL.EPOLL_D_STATO_POLL ( 
	COD_STATO varchar(50) NOT NULL,
	DESCRIZIONE varchar(200) NOT NULL
)
;

CREATE TABLE EPOLL.EPOLL_D_ALGORITMO_VOTAZIONE(
	COD_ALGORITMO varchar(50) NOT NULL,
	DESCRIZIONE varchar(200) NOT NULL,
	CONSTRAINT PK_EPOLL_D_ALGORITMO_VOTAZIONE PRIMARY KEY (COD_ALGORITMO)
)
;

CREATE TABLE EPOLL.EPOLL_T_PEC_CFG ( 
	ID bigint NOT NULL,
	ID_ENTE bigint NOT NULL,
	INDIRIZZO_PEC varchar(300) NOT NULL,
	IMAP_SERVER_HOSTNAME varchar(200) NOT NULL,
	IMAP_SERVER_PORT integer NOT NULL,
	IMAP_INBOX_FOLDER varchar(200) NOT NULL,
	IMAP_USERNAME varchar(200) NOT NULL,
	IMAP_PASSWORD bytea NOT NULL,
	SMTP_SERVER_HOSTNAME varchar(200) NOT NULL,
	SMTP_SERVER_PORT integer NOT NULL,
	SMTP_USERNAME varchar(200) NOT NULL,
	SMTP_PASSWORD bytea NOT NULL,
	FLAG_DEBUG boolean DEFAULT false NOT NULL
)
;

-- tables
CREATE TABLE EPOLL.EPOLL_T_ELETTORE ( 
	ID bigint NOT NULL,
	POLL_ID bigint NOT NULL,
	EMAIL varchar(300) NOT NULL,
	COGNOME_NOME varchar(200),
	DT_DATA_VOTAZIONE timestamp
)
;

CREATE TABLE EPOLL.EPOLL_T_ENTE ( 
	ID bigint NOT NULL,
	CODICE varchar(50) NOT NULL,
	COD_FISCALE varchar(50),
	DESCRIZIONE varchar(200),
	COD_ALGORITMO varchar(50)
)
;

CREATE TABLE EPOLL.EPOLL_T_POLL ( 
	ID bigint NOT NULL,
	ID_ENTE bigint NOT NULL,
	CODICE varchar(50) NOT NULL,
	OGGETTO varchar(200) NOT NULL,
	DT_INIZIO_VALIDITA timestamp NOT NULL,
	DT_FINE_VALIDITA timestamp NOT NULL,
	DT_CREAZIONE timestamp NOT NULL,
	TESTO text NOT NULL,
	ID_PRESIDENTE bigint NOT NULL,
	COD_STATO varchar(50) NOT NULL,
	NUMERO_MAX_PREFERENZE int4
)
;

CREATE TABLE EPOLL.EPOLL_T_PREFERENZA ( 
	ID bigint NOT NULL,
	POLL_ID bigint NOT NULL,
	PREFERENZA varchar(1000) NOT NULL,
	COD_PREFERENZA varchar(20) 
)
;

CREATE TABLE EPOLL.EPOLL_T_PREFERENZA_ESPRESSA ( 
	UUID varchar(100) NOT NULL,
	POLL_ID bigint NOT NULL,
	PREFERENZA varchar(1000) NOT NULL,
	CONTEGGIO integer NOT NULL,
	VALIDO boolean NOT NULL
)
;

CREATE TABLE EPOLL.EPOLL_T_PRESIDENTE ( 
	ID bigint NOT NULL,
	ID_ENTE bigint NOT NULL,
	COGNOME_NOME varchar(200) NOT NULL,
	EMAIL varchar(300) NOT NULL
)
;

CREATE TABLE EPOLL.EPOLL_T_BODY_PREFERENZA (
	ID bigint NOT NULL,
	ID_POLL int8 NOT NULL,
	BODY_PREFERENZA text NOT NULL,
	CONSTRAINT PK_EPOLL_T_BODY_PREFERENZA PRIMARY KEY (ID)
)
;

ALTER TABLE EPOLL.EPOLL_D_STATO_POLL ADD CONSTRAINT PK_EPOLL_D_STATO_POLL 

	PRIMARY KEY (COD_STATO)
;

ALTER TABLE EPOLL.EPOLL_T_ELETTORE ADD CONSTRAINT PK_EPOLL_T_ELETTORE 
	PRIMARY KEY (ID)
;


ALTER TABLE EPOLL.EPOLL_T_ENTE ADD CONSTRAINT PK_EPOLL_T_ENTE 
	PRIMARY KEY (ID)
;


ALTER TABLE EPOLL.EPOLL_T_POLL ADD CONSTRAINT PK_EPOLL_T_POLL 
	PRIMARY KEY (ID)
;


ALTER TABLE EPOLL.EPOLL_T_PREFERENZA ADD CONSTRAINT PK_EPOLL_T_PREFERENZA 
	PRIMARY KEY (ID)
;


ALTER TABLE EPOLL.EPOLL_T_PREFERENZA_ESPRESSA ADD CONSTRAINT PK_EPOLL_T_PREFERENZA_ESPRESSA
	PRIMARY KEY (UUID)
;


ALTER TABLE EPOLL.EPOLL_T_PRESIDENTE ADD CONSTRAINT PK_EPOLL_T_PRESIDENTE 
	PRIMARY KEY (ID)
;


ALTER TABLE EPOLL.EPOLL_T_ENTE
	ADD CONSTRAINT UQ_EPOLL_T_ENTE_CODICE UNIQUE (CODICE)
;
ALTER TABLE EPOLL.EPOLL_T_POLL
	ADD CONSTRAINT UQ_EPOLL_T_POLL_CODICE UNIQUE (CODICE)
;

ALTER TABLE EPOLL.EPOLL_T_ELETTORE ADD CONSTRAINT FK_EPOLL_T_ELETTORE_VOTA_T_POLL 
	FOREIGN KEY (POLL_ID) REFERENCES EPOLL.EPOLL_T_POLL (ID)
;

ALTER TABLE EPOLL.EPOLL_T_POLL ADD CONSTRAINT FK_EPOLL_T_POLL_VOTA_T_ENTE 
	FOREIGN KEY (ID_ENTE) REFERENCES EPOLL.EPOLL_T_ENTE (ID)
;

ALTER TABLE EPOLL.EPOLL_T_PEC_CFG ADD CONSTRAINT PK_EPOLL_T_PEC_CFG 
	PRIMARY KEY (ID)
;

ALTER TABLE EPOLL.EPOLL_T_PEC_CFG ADD CONSTRAINT FK_EPOLL_T_PEC_CFG_EPOLL_T_ENTE 
	FOREIGN KEY (ID_ENTE) REFERENCES EPOLL.EPOLL_T_ENTE (ID)
;

ALTER TABLE EPOLL.EPOLL_T_POLL ADD CONSTRAINT FK_EPOLL_T_POLL_VOTA_T_PRESIDENTE 
	FOREIGN KEY (ID_PRESIDENTE) REFERENCES EPOLL.EPOLL_T_PRESIDENTE (ID)
;

ALTER TABLE EPOLL.EPOLL_T_PREFERENZA ADD CONSTRAINT FK_EPOLL_T_PREFERENZA_VOTA_T_POLL 
	FOREIGN KEY (POLL_ID) REFERENCES EPOLL.EPOLL_T_POLL (ID)
;

ALTER TABLE EPOLL.EPOLL_T_PREFERENZA_ESPRESSA ADD CONSTRAINT FK_EPOLL_T_PREFERENZA_ESPRESSA_VOTA_T_POLL 
	FOREIGN KEY (POLL_ID) REFERENCES EPOLL.EPOLL_T_POLL (ID)
;

ALTER TABLE EPOLL.EPOLL_T_PRESIDENTE ADD CONSTRAINT FK_EPOLL_T_PRESIDENTE_VOTA_T_ENTE 
	FOREIGN KEY (ID_ENTE) REFERENCES EPOLL.EPOLL_T_ENTE (ID)
;

ALTER TABLE EPOLL.EPOLL_T_POLL ADD CONSTRAINT FK_EPOLL_T_POLL_EPOLL_D_STATO_POLL 
	FOREIGN KEY (COD_STATO) REFERENCES EPOLL.EPOLL_D_STATO_POLL (COD_STATO)
;