-- SPDX-FileCopyrightText: (C) Copyright 2021 CSI Piemonte
--
-- SPDX-License-Identifier: EUPL-1.2

INSERT INTO EPOLL.EPOLL_T_ENTE (ID, CODICE, COD_FISCALE, DESCRIZIONE, COD_ALGORITMO) VALUES (1, 'E1', '00000000000', 'Ente 1', 'SINGLE');
INSERT INTO EPOLL.EPOLL_T_ENTE (ID, CODICE, COD_FISCALE, DESCRIZIONE, COD_ALGORITMO) VALUES (2, 'E2', '00000000001', 'Ente multi', 'MULTI');

INSERT INTO EPOLL.EPOLL_T_PEC_CFG(ID,ID_ENTE,INDIRIZZO_PEC,IMAP_SERVER_HOSTNAME,IMAP_SERVER_PORT,IMAP_INBOX_FOLDER,IMAP_USERNAME,IMAP_PASSWORD,SMTP_SERVER_HOSTNAME,SMTP_SERVER_PORT,SMTP_USERNAME,SMTP_PASSWORD)
VALUES(1, 1, 'xxxxxxxxxxxxxxx@yyyyyy', 'host.it', 993, 'inbox', 'XXXXXXXXXXXXXXX', STRINGTOUTF8('SECRET'), 'host.it', 465, 'XXXXXXXX', STRINGTOUTF8('SECRET') );

INSERT INTO EPOLL.EPOLL_T_PRESIDENTE (ID, ID_ENTE, COGNOME_NOME, EMAIL) VALUES (1, 1, 'Test Utente 1', 'test1@cert.csi.it');

INSERT INTO EPOLL.EPOLL_D_STATO_POLL(COD_STATO, DESCRIZIONE) VALUES ('C', 'Creato');
INSERT INTO EPOLL.EPOLL_D_STATO_POLL(COD_STATO, DESCRIZIONE) VALUES ('S', 'Scrutinato');

INSERT INTO EPOLL.EPOLL_D_ALGORITMO_VOTAZIONE (COD_ALGORITMO, DESCRIZIONE) VALUES('SINGLE', 'Algoritmo di registrazione della preferenza singola');
INSERT INTO EPOLL.EPOLL_D_ALGORITMO_VOTAZIONE (COD_ALGORITMO, DESCRIZIONE) VALUES('MULTI', 'Algoritmo di registrazione della preferenza multipla');

INSERT INTO EPOLL.EPOLL_T_POLL (ID, ID_ENTE, CODICE, OGGETTO, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA, DT_CREAZIONE, TESTO, ID_PRESIDENTE, COD_STATO) VALUES (1, 1, 'POLL_1', 'Votazione di prova 1 per test ricezione mail', '2020-01-01 00:00:00.123456789', '2030-01-01 12:00:00.123456789', '2020-01-01 00:00:00.123456789', 'Siete chiamati a votare per il poll di prova 1', 1, 'C');
INSERT INTO EPOLL.EPOLL_T_POLL (ID, ID_ENTE, CODICE, OGGETTO, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA, DT_CREAZIONE, TESTO, ID_PRESIDENTE, COD_STATO) VALUES (2, 1, 'POLL_VINCE_GIALLO', 'Votazione di prova, vince giallo', '2020-01-01 00:00:00.123456789', '2021-01-01 12:00:00.123456789', '2020-01-01 00:00:00.123456789', 'Siete chiamati a votare per il poll di prova, tanto vince il giallo', 1, 'C');
INSERT INTO EPOLL.EPOLL_T_POLL (ID, ID_ENTE, CODICE, OGGETTO, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA, DT_CREAZIONE, TESTO, ID_PRESIDENTE, COD_STATO) VALUES (3, 1, 'POLL_EX_AEQUO_GIALLO_VERDE', 'Votazione di prova, giallo e verde pari', '2020-01-01 00:00:00.123456789', '2030-01-01 12:00:00.123456789', '2020-01-01 00:00:00.123456789', 'Siete chiamati a votare per il poll di prova, giallo e verde sono pari', 1, 'C');
INSERT INTO EPOLL.EPOLL_T_POLL (ID, ID_ENTE, CODICE, OGGETTO, DT_INIZIO_VALIDITA, DT_FINE_VALIDITA, DT_CREAZIONE, TESTO, ID_PRESIDENTE, COD_STATO) VALUES (4, 1, 'POLL_NO_PREF_VALIDE', 'Votazione di prova, nessuna preferenza valida', '2020-01-01 00:00:00.123456789', '2030-01-01 12:00:00.123456789', '2020-01-01 00:00:00.123456789', 'Siete chiamati a votare per il poll di prova, nessuna preferenza valida', 1, 'C');


INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (1, 1, 'Giallo');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (2, 1, 'Blu');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (3, 1, 'Verde');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (4, 2, 'Giallo');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (5, 2, 'Blu');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (6, 2, 'Verde');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (7, 3, 'Giallo');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (8, 3, 'Blu');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (9, 3, 'Verde');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (10, 4, 'Giallo');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (11, 4, 'Blu');
INSERT INTO EPOLL.EPOLL_T_PREFERENZA(ID, POLL_ID, PREFERENZA) VALUES (12, 4, 'Verde');

INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid1', '2', 'Blu', 6, true);
INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid2', '2', 'Giallo', 374, true);
INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid3', '2', 'Rosso', 4, false);
INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid4', '2', 'Verde', 7, true);

INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid5', '3', 'Blu', 6, true);
INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid6', '3', 'Giallo', 7, true);
INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid7', '3', 'Rosso', 4, false);
INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid8', '3', 'Verde', 7, true);

INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid9', '4', 'Bianco', 6, false);
INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid10', '4', 'Viola', 7, false);
INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid11', '4', 'Rosso', 4, false);
INSERT INTO EPOLL.EPOLL_T_PREFERENZA_ESPRESSA(UUID, POLL_ID, PREFERENZA, CONTEGGIO, VALIDO) VALUES ('uuid12', '4', 'Azzurro', 7, false);


INSERT INTO EPOLL.EPOLL_T_ELETTORE(ID, POLL_ID, EMAIL, COGNOME_NOME, DT_DATA_VOTAZIONE) VALUES (1, 1, 'email@email.it', 'xxxxxxxxxxxxxxxxxxxxx', NULL); 









