-- SPDX-FileCopyrightText: (C) Copyright 2021 CSI Piemonte
--
-- SPDX-License-Identifier: EUPL-1.2

CREATE TABLE EPOLL_D_ALGORITMO_VOTAZIONE ( 
	COD_ALGORITMO varchar(50) NOT NULL,
	DESCRIZIONE varchar(200) NOT NULL
)
;

INSERT INTO EPOLL_D_ALGORITMO_VOTAZIONE (COD_ALGORITMO, DESCRIZIONE) VALUES ('SINGLE', 'Algoritmo di registrazione della preferenza singola');
INSERT INTO EPOLL_D_ALGORITMO_VOTAZIONE (cod_algoritmo,descrizione) VALUES ('MULTI','Algoritmo di registrazione della preferenza multipla');

CREATE TABLE EPOLL_T_BODY_PREFERENZA ( 
	ID bigserial NOT NULL,
	ID_POLL bigint NOT NULL,
	BODY_PREFERENZA text NOT NULL
)
;

ALTER TABLE EPOLL_T_ENTE ADD COLUMN COD_ALGORITMO varchar(50) NOT NULL DEFAULT 'SINGLE'
;

ALTER TABLE EPOLL_T_POLL ADD COLUMN NUMERO_MAX_PREFERENZE INT DEFAULT 1;

ALTER TABLE EPOLL_D_ALGORITMO_VOTAZIONE ADD CONSTRAINT PK_EPOLL_D_ALGORITMO_VOTAZIONE 
	PRIMARY KEY (COD_ALGORITMO)
;

ALTER TABLE EPOLL_T_BODY_PREFERENZA ADD CONSTRAINT PK_EPOLL_T_BODY_PREFERENZA 
	PRIMARY KEY (ID)
;

ALTER TABLE EPOLL_T_BODY_PREFERENZA ADD CONSTRAINT FK_EPOLL_T_BODY_PREFERENZA_EPOLL_T_POLL 
	FOREIGN KEY (ID_POLL) REFERENCES EPOLL_T_POLL (ID)
;

ALTER TABLE EPOLL_T_ENTE ADD CONSTRAINT FK_EPOLL_T_ENTE_EPOLL_D_ALGORITMO_VOTAZIONE 
	FOREIGN KEY (COD_ALGORITMO) REFERENCES EPOLL_D_ALGORITMO_VOTAZIONE (COD_ALGORITMO)
;

ALTER TABLE EPOLL_T_PREFERENZA ADD COD_PREFERENZA varchar(20) NULL;
