-- SPDX-FileCopyrightText: (C) Copyright 2021 CSI Piemonte
--
-- SPDX-License-Identifier: EUPL-1.2

INSERT INTO EPOLL_D_STATO_POLL(COD_STATO, DESCRIZIONE) VALUES ('C', 'Creato');
INSERT INTO EPOLL_D_STATO_POLL(COD_STATO, DESCRIZIONE) VALUES ('S', 'Scrutinato');