-- SPDX-FileCopyrightText: (C) Copyright 2021 CSI Piemonte
--
-- SPDX-License-Identifier: EUPL-1.2

DROP TABLE IF EXISTS EPOLL_D_STATO_POLL CASCADE
;
DROP TABLE IF EXISTS EPOLL_T_ELETTORE CASCADE
;
DROP TABLE IF EXISTS EPOLL_T_ENTE CASCADE
;
DROP TABLE IF EXISTS EPOLL_T_PEC_CFG CASCADE
;
DROP TABLE IF EXISTS EPOLL_T_POLL CASCADE
;
DROP TABLE IF EXISTS EPOLL_T_PREFERENZA CASCADE
;
DROP TABLE IF EXISTS EPOLL_T_PREFERENZA_ESPRESSA CASCADE
;
DROP TABLE IF EXISTS EPOLL_T_PRESIDENTE CASCADE
;

CREATE TABLE EPOLL_D_STATO_POLL ( 
	COD_STATO varchar(50) NOT NULL,
	DESCRIZIONE varchar(200) NOT NULL
)
;

CREATE TABLE EPOLL_T_ELETTORE ( 
	ID bigserial NOT NULL,
	POLL_ID bigint NOT NULL,
	EMAIL varchar(300) NOT NULL,
	COGNOME_NOME varchar(200),
	DT_DATA_VOTAZIONE timestamp
)
;

CREATE TABLE EPOLL_T_ENTE ( 
	ID bigserial NOT NULL,
	CODICE varchar(50) NOT NULL,
	COD_FISCALE varchar(50),
	DESCRIZIONE varchar(200)
)
;

CREATE TABLE EPOLL_T_PEC_CFG ( 
	ID bigserial NOT NULL,
	ID_ENTE bigint NOT NULL,
	INDIRIZZO_PEC varchar(300) NOT NULL,
	IMAP_SERVER_HOSTNAME varchar(200) NOT NULL,
	IMAP_SERVER_PORT integer NOT NULL,
	IMAP_INBOX_FOLDER varchar(200) NOT NULL,
	IMAP_USERNAME varchar(200) NOT NULL,
	IMAP_PASSWORD bytea NOT NULL,
	SMTP_SERVER_HOSTNAME varchar(200) NOT NULL,
	SMTP_SERVER_PORT integer NOT NULL,
	SMTP_USERNAME varchar(200) NOT NULL,
	SMTP_PASSWORD bytea NOT NULL,
	FLAG_DEBUG boolean DEFAULT false NOT NULL
)
;

CREATE TABLE EPOLL_T_POLL ( 
	ID bigserial NOT NULL,
	ID_ENTE bigint NOT NULL,
	CODICE varchar(50) NOT NULL,
	OGGETTO varchar(200) NOT NULL,
	DT_INIZIO_VALIDITA timestamp NOT NULL,
	DT_FINE_VALIDITA timestamp NOT NULL,
	DT_CREAZIONE timestamp NOT NULL,
	TESTO text NOT NULL,
	ID_PRESIDENTE bigint NOT NULL,
	COD_STATO varchar(50) NOT NULL
)
;

CREATE TABLE EPOLL_T_PREFERENZA ( 
	ID bigserial NOT NULL,
	POLL_ID bigint NOT NULL,
	PREFERENZA varchar(1000) NOT NULL
)
;

CREATE TABLE EPOLL_T_PREFERENZA_ESPRESSA ( 
	UUID varchar(100) NOT NULL,
	POLL_ID bigint NOT NULL,
	PREFERENZA varchar(1000) NOT NULL,
	CONTEGGIO integer NOT NULL,
	VALIDO boolean NOT NULL
)
;

CREATE TABLE EPOLL_T_PRESIDENTE ( 
	ID bigserial NOT NULL,
	ID_ENTE bigint NOT NULL,
	COGNOME_NOME varchar(200) NOT NULL,
	EMAIL varchar(300) NOT NULL
)
;


ALTER TABLE EPOLL_D_STATO_POLL ADD CONSTRAINT PK_EPOLL_D_STATO_POLL 
	PRIMARY KEY (COD_STATO)
;


ALTER TABLE EPOLL_T_ELETTORE ADD CONSTRAINT PK_EPOLL_T_ELETTORE 
	PRIMARY KEY (ID)
;


ALTER TABLE EPOLL_T_ENTE ADD CONSTRAINT PK_EPOLL_T_ENTE 
	PRIMARY KEY (ID)
;


ALTER TABLE EPOLL_T_PEC_CFG ADD CONSTRAINT PK_EPOLL_T_PEC_CFG 
	PRIMARY KEY (ID)
;


ALTER TABLE EPOLL_T_POLL ADD CONSTRAINT PK_EPOLL_T_POLL 
	PRIMARY KEY (ID)
;


ALTER TABLE EPOLL_T_PREFERENZA ADD CONSTRAINT PK_EPOLL_T_PREFERENZA 
	PRIMARY KEY (ID)
;


ALTER TABLE EPOLL_T_PREFERENZA_ESPRESSA ADD CONSTRAINT PK_EPOLL_T_PREFERENZA 
	PRIMARY KEY (UUID)
;


ALTER TABLE EPOLL_T_PRESIDENTE ADD CONSTRAINT PK_EPOLL_T_PRESIDENTE 
	PRIMARY KEY (ID)
;



ALTER TABLE EPOLL_T_ENTE
	ADD CONSTRAINT UQ_EPOLL_T_ENTE_CODICE UNIQUE (CODICE)
;
ALTER TABLE EPOLL_T_POLL
	ADD CONSTRAINT UQ_EPOLL_T_POLL_CODICE UNIQUE (CODICE)
;

ALTER TABLE EPOLL_T_PEC_CFG ADD CONSTRAINT FK_EPOLL_T_PEC_CFG_EPOLL_T_ENTE 
	FOREIGN KEY (ID_ENTE) REFERENCES EPOLL_T_ENTE (ID)
;

ALTER TABLE EPOLL_T_POLL ADD CONSTRAINT FK_EPOLL_T_POLL_EPOLL_D_STATO_POLL 
	FOREIGN KEY (COD_STATO) REFERENCES EPOLL_D_STATO_POLL (COD_STATO)
;

ALTER TABLE EPOLL_T_PREFERENZA ADD CONSTRAINT FK_EPOLL_T_PREFERENZA_EPOLL_T_POLL 
	FOREIGN KEY (POLL_ID) REFERENCES EPOLL_T_POLL (ID)
;

ALTER TABLE EPOLL_T_PREFERENZA_ESPRESSA ADD CONSTRAINT FK_EPOLL_T_PREFERENZA_ESPRESSA_EPOLL_T_POLL 
	FOREIGN KEY (POLL_ID) REFERENCES EPOLL_T_POLL (ID)
;

;ALTER TABLE EPOLL_T_ELETTORE ADD CONSTRAINT FK_EPOLL_T_ELETTORE_VOTA_T_POLL 
	FOREIGN KEY (POLL_ID) REFERENCES EPOLL_T_POLL (ID)
;

ALTER TABLE EPOLL_T_POLL ADD CONSTRAINT FK_EPOLL_T_POLL_VOTA_T_PRESIDENTE 
	FOREIGN KEY (ID_PRESIDENTE) REFERENCES EPOLL_T_PRESIDENTE (ID)
;

ALTER TABLE EPOLL_T_PRESIDENTE ADD CONSTRAINT FK_EPOLL_T_PRESIDENTE_VOTA_T_ENTE 
	FOREIGN KEY (ID_ENTE) REFERENCES EPOLL_T_ENTE (ID)
;

ALTER TABLE EPOLL_T_POLL ADD CONSTRAINT FK_EPOLL_T_POLL_VOTA_T_ENTE 
	FOREIGN KEY (ID_ENTE) REFERENCES EPOLL_T_ENTE (ID)
;